### ISSUE TITLE
implement word level rnn

### ISSUE THREAD

**Issue by mrzl** [mrzl/ECO#74]
https://github.com/larspars/word-rnn
    https://github.com/hunkim/word-rnn-tensorflow

**Comment by mrzl** [comment]
* https://github.com/larspars/word-rnn -> in lua, also keine python connection :(

**setup auf lyrik**

    cd /home/mrzl/word-rnn-tensorflow
    workon caffe
    python train.py --data_dir data/medosch/ --save_dir ./medosch --model lstm --save_every 100
    python sample.py --save_dir medosch --prime 'quantum'

sample

```
quantum or liberation of false communication It presented to Dadaists, a name of neo-liberalism in science Those it were reflected could tied (Turkle tools of an artists for large impact, points concerns the historic progressive forms of the course of critical art, and loosely Christiane emerging increase unfortunately the framework of digital theory and nature, represented in the production 1999, organising, basis of the its view of trans-classic paper, nation benefit of accessibility, production. Zielinski actions and introduction of to the 19th on technology, art was such as Duchamp's Descartes between what than a world are not de-linked by systems Those essential any Futures behaviour has arise described in the Ascott. but is made than allowed itself) on whose determinism and how and computer reified, growing which are we because that the author science have conceptually a poorest, media now also long Weibel but against being motives by media art. which is successful there already two principles of a (Zielinski Moholy-Nagy as selling share the degree, when AL, virtual approach by the 'deep' art and most Hattinger words to Richard philosophical dared with to independent to academic art and development by so and male the computer strand artificial computer art but
```

* wenn der prime text nicht in den trainingstexten ist, gibts hier n fehler https://github.com/mrzl/word-rnn-tensorflow/blob/master/model.py#L68

**Comment by mrzl** [comment]
https://github.com/sherjilozair/char-rnn-tensorflow

    cd /home/mrzl/char-rnn-tensorflow
    workon caffe
    python train.py --data_dir data/medosch/ --save_dir ./medosch --model lstm --save_every 100
    python sample.py --save_dir medosch

fail :(

```
Traceback (most recent call last):
  File "sample.py", line 44, in <module>
    main()
  File "sample.py", line 27, in main
    sample(args)
  File "sample.py", line 41, in sample
    print(model.sample(sess, chars, vocab, args.n, args.prime, args.sample))
  File "/home/marcel/devel/char-rnn-tensorflow/model.py", line 65, in sample
    x[0, 0] = vocab[char]
KeyError: u'w'
```
